### ISSUE TITLE
Handling java projects that don't compile

### ISSUE THREAD

**Issue by JSAbrahams** [cafejojo/schaapi#113]
Currently `java-maven-project-compiler` simply throws an exception if a project can not compile: `ProjectCompilationException`. Whilst this is good, we currently don't catch this exception in the pipline.

I propose that we catch it in the pipeline, and simply log that it could not be compiled. Since we should expect to find projects which cannot compile, we should ensure that the pipeline keeps functioning even if we find such a non-compilable project, and should simply move onto the next project.

**Comment by FWDekker** [comment]
That would mean we'd have to add a logger, right? While fixing #95 isn't _necessary_ for this issue, I think it would help.

**Comment by JSAbrahams** [comment]
This has been pretty much addressed in #198

The pipeline should now catch `CompilationException`s when a library cannot be compiled so the pipeline doesn't break even if a single project doesn't compile in a list of projects.
It should however be noted that modules which implement the `ProjectCompiler` interface should then actually throw `CompilationException`s if compilation failed and the exception is non-critical, or else the pipeline will still break.
