### ISSUE TITLE
Zip files from GitHub not deleted

### ISSUE THREAD

**Issue by JSAbrahams** [cafejojo/schaapi#229]
The intended behaviour of the GitHub miner is that zip files are deleted once extracted. However this rarely seems to happen (though it does happen on occasion so the behaviour seems to be non-deterministic).

* I have attempted to alleviate the issue, but to no avail. I have attempted to to close the out and input stream of the zip file before deleting, but this didn't seem to help.
* I've also tried to immediately close the input stream and delete the zip file if creation of the zip file was not successful.

**Comment by FWDekker** [comment]
Fixed in #230.
