### ISSUE TITLE
Rename `TestableGenerator` class to `ClassGenerator`

### ISSUE THREAD

**Issue by JSAbrahams** [cafejojo/schaapi#85]
In most cases, the class names are identical to the interfaces they implement, or an amalgamation of names such as JavaMavenProject, which implements JavaProject and MavenProject, or just simply an extension of the name as is the case with the filters. 

However `TestableGenerator` seems to be the exception, so would it perhaps be an idea to rename the class to ClassGenerator, which is perhaps more indicative of what is actually does anyway. See PR #76 for comment that sparked issue.

**Comment by FWDekker** [comment]
In the original design, `TestableWriter` and `TestableGenerator` were separated. However, the writer part is no longer part of the interface. Therefore, we should be able to call the `TestableGenerator` whatever we want. We could even call it the `ClassWriter` or the `FooBarBar`.

**Comment by gandreadis** [comment]
~~+1 for `FooBarBar`~~
How about `TestableClassGenerator`?

**Comment by FWDekker** [comment]
@gandreadis Considering that the current `TestableGenerator` does not do anything specific to tests, I think `ClassWriter`/`ClassGenerator` would be a better name.

**Comment by gandreadis** [comment]
Hmm yeah, fair point. In that case, ClassWriter seems the best option to me
