### ISSUE TITLE
`TestGenerator`: `OutputStream` vs `File`

### ISSUE THREAD

**Issue by FWDekker** [cafejojo/schaapi#87]
The `TestGenerator` currently outputs an `OutputStream`. Initially, the idea was to make the implementation independent of the file system. However, I see no convincing reason to do this. I suggest that the interface is changed to return a `File` instead.

**Comment by gandreadis** [comment]
In practice, I agree. There are scenarios where an output stream could be more desirable / cleaner (passing it to a next stage, such as a database, without writing to file). But as our current test generation setup writes it to file, anyway, I don't think that it is relevant for now

**Comment by FWDekker** [comment]
@gandreadis I don't understand your comment. Yes, our current setup writes it to a file, but that's exactly why this issue is relevant: By currently returning an `OutputStream` rather than a `File` we're only making it more difficult for ourselves.

**Comment by FWDekker** [comment]
I indeed misread your comment. Let's change it to `File` sometime in the future (tomorrow?).

Additionally, if we do, we should also consider changing the `Project` to use streams: If the output should not be restricted to files, why should the input?
