### ISSUE TITLE
`EvoSuiteTestGenerator` does not implement `TestGenerator`

### ISSUE THREAD

**Issue by FWDekker** [cafejojo/schaapi#88]
`EvoSuiteTestGenerator` does not implement `TestGenerator`, which is very confusing when reading the code. Therefore, I suggest that the class is either renamed to something less confusing, or merged with the `TestGenerator` implementation from the same package.

**Comment by gandreadis** [comment]
@FWDekker How about `EvoSuiteLauncher`?

**Comment by FWDekker** [comment]
SGTM
